### ISSUE TITLE
Q: is there some issue with "debug" gem bundled with ruby 3.2.x

### ISSUE THREAD

**Issue by kikonen** [ruby/debug#898]
**Your environment**

* `ruby -v`:  3.2.1
* `rdbg -v`: 1.7.1

**Describe the bug**

Encountering strange problem in circleci due to debug gem,

```
Downloading debug-1.7.1 revealed dependencies not in the API or the lockfile
(irb (>= 1.5.0), reline (>= 0.3.1)).
Either installing with `--full-index` or running `bundle update debug` should
fix the problem.
```

i.e. there is no such dependencies in Gemfile.lock generated by bundler in ruby 3.2, I see that in rubygems such dependencies are listed, so is there something wrong with this version "debug" bundled into ruby 3.2.1?

In Gemfile
```
gem 'debug'
```

In Gemfile.lock
```
GEM
...
    debug (1.7.1)
...
DEPENDENCIES
  debug
...
BUNDLED WITH
   2.4.6
```
Thus no dependencies

**To Reproduce**

in circleci when using gem caching this triggers
```
version: 2
jobs:
  test:
    docker:
      - image: ruby:3.2.1
        environment:
          RUBY_YJIT_ENABLE: 'true'
      - restore_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install gems
          command: |
            ruby --version
            bundle config set --local path vendor/bundle
            bundle check || bundle install --jobs=4 --retry=3
      - save_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
```

**Expected behavior**

Clearly I would expect to not get such obscure error, which clearly should not exist

**Additional context**

Have spent now one day of trying to figure out how to make this work, I don't want to remove "debug" gem, since would fix problem, but then I loose debugger

**Comment by doits** [comment]
Same for me. The error only happened on CI for me though, locally it installed fine 🤷 . I removed the gem for the time beeing.

**Comment by gregawoods** [comment]
Same. Locking debug to version 1.6.1 in my Gemfile has worked for the time being.

**Comment by deivid-rodriguez** [comment]
I believe this is an upstream issue, I reported it [a while ago](https://bugs.ruby-lang.org/issues/19158). You can find a workaround [here](https://github.com/ruby/debug/issues/852#issuecomment-1431872261).

**Comment by hsbt** [comment]
I fixed this issue at https://bugs.ruby-lang.org/issues/19158#note-10. We need to test it with Ruby 3.2 and backport, cut a new release.

**Comment by searls** [comment]
@hsbt thank you!! 💚

**Comment by kikonen** [comment]
Lovely

**Comment by doits** [comment]
Thanks for your help!

FYI I could fix it by:

- `gem uninstall debug`
- `bundle update` (which reinstalls `debug` with correct dependencies)

**Comment by brand-it** [comment]
Came here running into this same problem. For sure there is something odd going on with the bundler and the lock file. I did not spend more than an hour on this problem before giving up and placing the required gems into the group.

### Steps to reproduce Locally 

1. ` bundle config --local deployment true`
2. bundle install
3. 😠 experience frustration(optional)

### Steps to reproduce GitHub actions

```yaml
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
```

I omitted the RSpec step but this will also get you the error if you set up this Github action on a repo

### "Solution"

My solution is sort of a solution but really this should be something the gem does so I came to the conclusion there is a bug in bundler(`2.4.7`)

```ruby
group :development, :test do
  gem 'debug'
  gem 'irb'
  gem 'reline'
end
```

![Screen Shot 2023-02-20 at 7 31 46 PM](https://user-images.githubusercontent.com/13140/220240704-77088e49-125c-4cb4-8cca-0343516a2baa.png)

I don't have an answer to why this is happening but because this gem is for local development I did not dust off many brain cell to figure it out. First time I have seen this hope it is the last. Thanks for the hard work on this gem.
